### ISSUE TITLE
TwigTemplate Hooks's no working

### ISSUE THREAD

**Issue by baumannsven** [contao-community-alliance/twig#10]
Hey,

can you extends this class with system or another.
$this->import() didn't work

MfG Sven

**Comment by tristanlins** [comment]
https://github.com/contao-community-alliance/twig/blob/master/src/ContaoTwig/TwigTemplate.php#L139

**Comment by tristanlins** [comment]
Fixed in https://github.com/contao-community-alliance/twig/commit/364375f63d7201269c9d6dac958468f06711d237
